###
http://localhost:8000/usuarios

###
http://localhost:8000

###
http://localhost:8000/usuarioss

###
http://localhost:8000/cualca

###
http://localhost:8000/usuari

###
http://localhost:8000/USUARIOS

###
http://localhost:8000/usuario

